### PR TITLE
remove Fixnum deprecation warning for ruby 2.4.0 (fixes #31)

### LINKED ISSUE #31: Ruby 2.4 Support
Fix Ruby 2.4 Fixnum deprecations

### PR DESCRIPTION
**Pull request by activefx**

### CODE REVIEW

**Comment by Tuxii** [comment]
Thanks for the PR, this needs to be merged !

**Comment by shaneog** [comment]
Ping!

**Comment by kke** [comment]
More ping.

**Comment by ernestas-poskus** [comment]
@phillbaker merge ?

**Comment by ernestas-poskus** [comment]
ping @nanzhong @vjustov @bobbytables

**Comment by kyrylo** [comment]
Hey guys, is this gem maintained? If not, it would probably make sense to fork it, but if it's still maintained, then forking wouldn't be necessary. I just wanted to clarify the status.

**Comment by vinc** [comment]
+1

**Pull request merged**
